version: '2'
services:
    db:
        image: mariadb
        ports: 
        - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: qitrw
          MYSQL_USER: qitrw
          MYSQL_PASSWORD: qitrw
        volumes:
        - ./bootstrap/db:/docker-entrypoint-initdb.d
    web:
        depends_on:
        - db
        image: wordpress
        links:
        - db
        ports:
        - 80:80
        environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: qitrw
          WORDPRESS_DB_PASSWORD: qitrw
          WORDPRESS_DB_NAME: qitrw
        volumes: 
        - ./build/www:/var/www/html
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        restart: always
        ports:
        - 8080:80
        volumes:
        - /sessions